# -*- coding: utf-8 -*-
"""Kalkulator Fungsi Kompleks .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ACloFP5jA8PddVbL8yji4gIitK_Tv05I
"""

import sympy as sp
import sympy as sp
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D  # untuk 3D plot


# Definisikan simbol
x, y = sp.symbols('x y', real=True)
z = sp.Symbol('z')  # simbol kompleks
z_subs = x + sp.I*y

# Input user
f_input = input("Masukkan fungsi f(z): ")
try:
    f_expr = sp.sympify(f_input)         # parsing string
    f_xy = f_expr.subs(z, z_subs)        # substitusi z = x + iy
    f_xy_expanded = sp.expand(f_xy)      # ekspansi penuh
    u = sp.re(f_xy_expanded)
    v = sp.im(f_xy_expanded)

    print("\n--- HASIL ---")
    print(f"f(z)        = {f_expr}")
    print(f"z = x + iy  → f(x + iy) = {f_xy_expanded}")
    print(f"u(x, y)     = {u}")
    print(f"v(x, y)     = {v}")
except Exception as e:
    print(f"Terjadi kesalahan saat memproses: {e}")



# Variabel simbolik
x, y = sp.symbols('x y', real=True)
z = x + sp.I*y

# Input fungsi dari user
f_input = f_xy_expanded
f_expr = sp.sympify(f_input)

# Pecah menjadi u dan v
u = sp.re(f_expr)
v = sp.im(f_expr)

# Input titik z0
x0 = float(input("Masukkan nilai x0: "))
y0 = float(input("Masukkan nilai y0: "))

# Hitung turunan parsial
du_dx = sp.diff(u, x)
du_dy = sp.diff(u, y)
dv_dx = sp.diff(v, x)
dv_dy = sp.diff(v, y)

# Evaluasi syarat Cauchy-Riemann di titik
du_dx_val = du_dx.subs({x: x0, y: y0})
du_dy_val = du_dy.subs({x: x0, y: y0})
dv_dx_val = dv_dx.subs({x: x0, y: y0})
dv_dy_val = dv_dy.subs({x: x0, y: y0})

cauchy_riemann = (sp.simplify(du_dx_val - dv_dy_val) == 0) and (sp.simplify(du_dy_val + dv_dx_val) == 0)

print("\n--- HASIL ---")
print(f"u(x, y) = {u}")
print(f"v(x, y) = {v}")
print(f"Cek syarat Cauchy-Riemann di ({x0}, {y0}): {cauchy_riemann}")

if cauchy_riemann:
    df_dz = du_dx_val + sp.I * dv_dx_val
    print(f"Fungsi terdiferensialkan kompleks di titik tersebut.")
    print(f"f'(z) = {df_dz}")
else:
    print("Fungsi TIDAK memenuhi syarat Cauchy-Riemann. Tidak terdiferensialkan kompleks di titik ini.")

# ----- GRAFIK U dan V -----
u_func = sp.lambdify((x, y), u, modules='numpy')
v_func = sp.lambdify((x, y), v, modules='numpy')

# Rentang koordinat
X_vals = np.linspace(-5, 5, 100)
Y_vals = np.linspace(-5, 5, 100)
X, Y = np.meshgrid(X_vals, Y_vals)

U_vals = u_func(X, Y)
V_vals = v_func(X, Y)

# Buat plot 3D
fig = plt.figure(figsize=(12, 5))

# Plot u(x,y)
ax1 = fig.add_subplot(1, 2, 1, projection='3d')
ax1.plot_surface(X, Y, U_vals, cmap='viridis')
ax1.set_title('Real part u(x, y)')
ax1.set_xlabel('x')
ax1.set_ylabel('y')
ax1.set_zlabel('u')

# Plot v(x,y)
ax2 = fig.add_subplot(1, 2, 2, projection='3d')
ax2.plot_surface(X, Y, V_vals, cmap='plasma')
ax2.set_title('Imaginary part v(x, y)')
ax2.set_xlabel('x')
ax2.set_ylabel('y')
ax2.set_zlabel('v')

plt.tight_layout()
plt.show()