# -*- coding: utf-8 -*-
"""Kalkulator Fungsi Kompleks .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ACloFP5jA8PddVbL8yji4gIitK_Tv05I
"""

import streamlit as st
import sympy as sp
import numpy as np
import matplotlib.pyplot as plt

# Judul aplikasi
st.title("Analisis Fungsi Kompleks f(z) dengan Streamlit")

# Input dari pengguna
f_input = st.text_input("Masukkan fungsi f(z):", value="z**2")

# Definisikan simbol
x, y = sp.symbols('x y', real=True)
z = x + sp.I*y
z_sym = sp.Symbol('z')

# Proses saat input tersedia
if f_input:
    try:
        # Ekspresi f(z)
        f_z = sp.sympify(f_input)

        # Substitusi z = x + iy untuk bentuk u + iv
        f_xy = f_z.subs({z_sym: z})
        f_xy_expanded = sp.expand(f_xy)

        # Pisahkan real dan imajiner
        u = sp.re(f_xy_expanded)
        v = sp.im(f_xy_expanded)

        # Turunan terhadap z (simbolik)
        f_deriv = sp.diff(f_z, z_sym)

        st.markdown("### ✨ Hasil Ekspansi dan Turunan")
        st.latex(f"f(z) = {sp.latex(f_z)}")
        st.latex(r"z = x + iy")
        st.latex(f"f(z) = {sp.latex(f_xy_expanded)}")
        st.latex(f"u(x, y) = {sp.latex(u)}")
        st.latex(f"v(x, y) = {sp.latex(v)}")
        st.latex(f"f'(z) = {sp.latex(f_deriv)}")

        # Checkbox untuk menampilkan grafik
        if st.checkbox("Tampilkan grafik u(x, y) dan v(x, y)"):
            # Buat fungsi numerik
            u_func = sp.lambdify((x, y), u, modules='numpy')
            v_func = sp.lambdify((x, y), v, modules='numpy')

            X_vals = np.linspace(-5, 5, 100)
            Y_vals = np.linspace(-5, 5, 100)
            X, Y = np.meshgrid(X_vals, Y_vals)

            try:
                U = u_func(X, Y)
                V = v_func(X, Y)

                fig = plt.figure(figsize=(12, 5))

                ax1 = fig.add_subplot(1, 2, 1, projection='3d')
                ax1.plot_surface(X, Y, U, cmap='viridis')
                ax1.set_title('Real part u(x, y)')
                ax1.set_xlabel('x')
                ax1.set_ylabel('y')
                ax1.set_zlabel('u')

                ax2 = fig.add_subplot(1, 2, 2, projection='3d')
                ax2.plot_surface(X, Y, V, cmap='plasma')
                ax2.set_title('Imaginary part v(x, y)')
                ax2.set_xlabel('x')
                ax2.set_ylabel('y')
                ax2.set_zlabel('v')

                st.pyplot(fig)

            except Exception as e:
                st.error(f"Terjadi kesalahan saat membuat grafik: {e}")

    except Exception as e:
        st.error(f"Gagal memproses fungsi: {e}")

